version: "3.7"
services:

  traefik:
    image: traefik:1.6
    depends_on:
      - log_collector
    ports:
      - target: 80
        protocol: tcp
        published: ${HOST_HTTP_PORT}
        mode: ingress
      - target: 443
        protocol: tcp
        published: ${HOST_HTTPS_PORT}
        mode: ingress
      - target: 8080
        protocol: tcp
        published: ${HOST_HEALTH_CHECK_PORT}
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse_proxy
    logging:
      driver: "fluentd"
      options:
        tag: reverse_proxy
    configs:
      - source: traefik_toml
        target: /etc/traefik/traefik.toml
        mode: 0444
    secrets:
      - source: doiex_crt
        target: doiex.crt
      - source: doiex_key
        target: doiex.key
      - source: doiex_root_crt
        target: doiex.root.crt
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
      placement:
        constraints: [node.role == manager]

networks:
  reverse_proxy:
    external: true
    driver: overlay

configs:
  traefik_toml:
    external: true

secrets:
  doiex_crt:
    external: true
  doiex_key:
    external: true
  doiex_root_crt:
    external: true
